version: "1.0"

services:

  mysql:
    image: mariadb:latest
    restart: always
    command: mysqld --sql_mode=""
    env_file:
      - env/mysql.env
    ports:
      - "3306:3306"

  backend:
    image: backend
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:43"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./src:/usr/share/nginx/html/project

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"